In [1]:
import numpy as np

In [2]:
my_array = np.array([10,20,30,40,50,60])

In [3]:
print(my_array)

[10 20 30 40 50 60]


In [4]:
my_array[4]

50

There are two ways to access Elements:
    1. Positive Indexing
    2. Negative Indexing
    
    1. 0-D
    2. 1-D
    3. 2-D
    4. 3-D

### 1. Python Array Slicing:
    1. Slicing in python means taking elements from one given index to another given index
    2. we pass slice insted indexes [start:end]
    3. we can also used like this [start: step : end]

### 1. Positive

In [5]:
my_array = np.array([10,20,30,40,50,60])

In [6]:
my_array[0:4]

array([10, 20, 30, 40])

In [7]:
my_array[0:5]

array([10, 20, 30, 40, 50])

In [8]:
my_array[:]

array([10, 20, 30, 40, 50, 60])

In [9]:
my_array[1:]

array([20, 30, 40, 50, 60])

### 2. Negative Indexing

In [10]:
my_array = np.array([10,20,30,40,50,60])

In [11]:
my_array[-1:]

array([60])

In [13]:
my_array[-5:-1]

array([20, 30, 40, 50])

In [14]:
my_array[:-1]

array([10, 20, 30, 40, 50])

In [17]:
my_array[-5:-2]

array([20, 30, 40])

## 3. Step

In [18]:
# [start:end:steps]
my_array = np.array([10,20,30,40,50,60,70,80,90,100])

In [19]:
my_array[::2]

array([10, 30, 50, 70, 90])

In [20]:
my_array = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16])

In [25]:
my_array[2::3]

array([ 3,  6,  9, 12, 15])

# 2. 2-D Array

In [26]:
my_array = np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [27]:
my_array[1, :2]

array([6, 7])

In [28]:
my_array[0,:]

array([1, 2, 3, 4, 5])

In [29]:
my_array[1, 1:]

array([ 7,  8,  9, 10])

In [30]:
my_array = np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [36]:
my_array[0:2,2:3]

array([[3],
       [8]])

In [39]:
my_array[0:1, 2:4]

array([[3, 4]])

In [41]:
# [dimension[start:end],[start:index]]

In [50]:
my_array = np.array([[1,2,3,4,5],[6,7,8,9,10],[4,5,6,8,9]])

In [52]:
my_array[0:3, : :3]

array([[1, 4],
       [6, 9],
       [4, 8]])

In [59]:
my_array = np.array([[1,2,3,4,5,57],[6,7,8,9,10,15],[4,5,6,8,9,45]])

In [63]:
my_array[1:3, 1:6:3]

array([[ 7, 10],
       [ 5,  9]])

# 3. 3-D Array

In [64]:
my_array = np.array([[[10,20,30,40,50],[60,70,80,90,100]],[[110,120,130,140,150],[12,15,17,16,45]]])

In [68]:
my_array[1:2, 0:1, ::2]

array([[[110, 130, 150]]])

In [72]:
my_array[0:1,1:,1:4]

array([[[70, 80, 90]]])

### Data Types in Python:
    1. string
    2. integer
    3. float
    4. boolean
    6. complex

In [74]:
# help(np)

## Numpy Data Types in Python:
    1. i - integer
    2. b - boolean
    3. u - unsigned integer
    4. f - float
    5. c - complex float
    6. m - timedelta
    7. M - Datatime
    8. O - object
    9. s - string
    10. uncode string
    11. Fixed chunk of memory 