### Joining Array Numpy

In [1]:
import numpy as np

In [2]:
my_array1 = np.array([10,20,30,40])
my_array2 = np.array([50,60,70,80])

new_array = my_array1 + my_array2
new_array


array([ 60,  80, 100, 120])

### 1. Concatenate 

In [3]:
my_array1 = np.array([10,20,30,40])
my_array2 = np.array([50,60,70,80])

new_array = np.concatenate((my_array1, my_array2))
print(new_array)

[10 20 30 40 50 60 70 80]


In [4]:
my_array1 = np.array([[10,20,30,40],[50,60,70,80]])
my_array2 = np.array([[50,60,70,80],[15,16,14,10]])

new_array = np.concatenate((my_array1, my_array2), axis=1)
print(new_array)

[[10 20 30 40 50 60 70 80]
 [50 60 70 80 15 16 14 10]]


### Array splitting in Numpy

In [5]:
my_array1 = np.array([10,20,30,40,50,60,70,80,90,100])

new_array = np.array_split(my_array1,3)

In [6]:
new_array

[array([10, 20, 30, 40]), array([50, 60, 70]), array([ 80,  90, 100])]

In [9]:
my_array1 = np.array([10,20,30,40,50,60,70,80,90,100,110])

new_array = np.array_split(my_array1,4)
new_array

[array([10, 20, 30]),
 array([40, 50, 60]),
 array([70, 80, 90]),
 array([100, 110])]

In [10]:
my_array1 = np.array([10,20,30,40,50,60,70,80,90])

new_array = np.array_split(my_array1,4)
new_array

[array([10, 20, 30]), array([40, 50]), array([60, 70]), array([80, 90])]

In [12]:
my_array1 = np.array([10,20,30,40,50,60,70,80,90,100,110])

new_array = np.array_split(my_array1,4)

print(new_array[0])
print(new_array[1])
print(new_array[2])
print(new_array[3])

[10 20 30]
[40 50 60]
[70 80 90]
[100 110]


In [14]:
my_array1 = np.array([10,20,30,40,50,60,70,80,90,100])

new_array = np.array_split(my_array1, 3)
print(new_array)

[array([10, 20, 30, 40]), array([50, 60, 70]), array([ 80,  90, 100])]


# 2-D Array

In [15]:
my_array1 = np.array([[10,20],[30,40],[50,60],[70,80],[90,100]])

new_array = np.array_split(my_array1, 3)
print(new_array)

[array([[10, 20],
       [30, 40]]), array([[50, 60],
       [70, 80]]), array([[ 90, 100]])]


In [19]:
print(new_array[0])
print(new_array[1])
print(new_array[2])

[[10 20]
 [30 40]]
[[50 60]
 [70 80]]
[[ 90 100]]


In [20]:
my_array1 = np.array([[10,20],[30,40],[50,60],[70,80],[90,100]])

new_array = np.array_split(my_array1, 3, axis=1)
print(new_array)

[array([[10],
       [30],
       [50],
       [70],
       [90]]), array([[ 20],
       [ 40],
       [ 60],
       [ 80],
       [100]]), array([], shape=(5, 0), dtype=int32)]


In [21]:
print(new_array[0])
print(new_array[1])
print(new_array[2])

[[10]
 [30]
 [50]
 [70]
 [90]]
[[ 20]
 [ 40]
 [ 60]
 [ 80]
 [100]]
[]


In [25]:
my_array1 = np.array([[10,20],[30,40],[50,60],[70,80],[90,100],[110,120]])

new_array = np.hsplit(my_array1, 2)
print(new_array)

[array([[ 10],
       [ 30],
       [ 50],
       [ 70],
       [ 90],
       [110]]), array([[ 20],
       [ 40],
       [ 60],
       [ 80],
       [100],
       [120]])]


In [27]:
my_array1 = np.array([[10,20],[30,40],[50,60],[70,80],[90,100],[110,120]])

new_array = np.vsplit(my_array1, 3)
print(new_array)

[array([[10, 20],
       [30, 40]]), array([[50, 60],
       [70, 80]]), array([[ 90, 100],
       [110, 120]])]


### Searcing Array in Numpy

In [33]:
my_array1 = np.array([10,20,30,40,50,60,70,80,90,100])

x = np.where(my_array1 == 40)
print(x)

(array([3], dtype=int64),)


In [36]:
# help(np.where(my_array1))

In [42]:
my_array1 = np.array([10,20,115,30,40,50,60,70,80,90,100,111,113])

x = np.where(my_array1%2 == 1)

print("All the Odd elements in Array are: ",x)

All the Odd elements in Array are:  (array([ 2, 11, 12], dtype=int64),)


In [43]:
my_array1 = np.array([10,20,115,30,40,50,60,70,80,90,100,111,113])

my_array1[1]

20