In [1]:
import numpy as np

In [2]:
my_array = np.array([10,20,42,15,48,75])

x = np.where(my_array == 15)
print(x)

(array([3], dtype=int64),)


In [3]:
my_array = np.array([10,20,42,15,48,75])

x = np.where(my_array%2 == 0)
print(x)

(array([0, 1, 2, 4], dtype=int64),)


In [4]:
my_array = np.array([10,20,42,15,48,75])

x = np.where(my_array%2 == 1)
print(x)

(array([3, 5], dtype=int64),)


### Search Sorted array in Numpy

![](https://www.geeksforgeeks.org/wp-content/uploads/Binary-Search.png)

In [19]:
my_array = np.array([10,15,20,23,26,42,48,63,75,98])

x = np.searchsorted(my_array, 63)
print(x)

7


In [20]:
# mid = l + (r - l) // 2

### Sort Array

In [21]:
my_array = np.array([12,46,52,78,62,75,32,52,17])

new_array = np.sort(my_array)

In [22]:
new_array

array([12, 17, 32, 46, 52, 52, 62, 75, 78])

In [26]:
my_array = np.array(['banana','pinapple','apple','cherry','watermelon','papya','APPLE', 'CHERRY'])

new_array = np.sort(my_array)
print(new_array)

['APPLE' 'CHERRY' 'apple' 'banana' 'cherry' 'papya' 'pinapple'
 'watermelon']


In [24]:
my_array = np.array([True, False, False, True, False])

new_array = np.sort(my_array)
print(new_array)

[False False False  True  True]


### Even odd 

In [28]:
my_array = np.array([12,46,52,78,62,75,32,52,17])

if my_array[1]%2 == 0:
    print("Even No")
else:
    print("Odd No")

Even No


In [29]:
my_array = np.array([12,46,52,78,62,75,32,52,17])

new_array = np.where(my_array%2 == 0)
new_array

(array([0, 1, 2, 3, 4, 6, 7], dtype=int64),)

In [33]:
my_array = np.array([12,46,96,78,62,75,32,52,17])

new_array = my_array % 2 == 0
output_array = my_array[new_array]

print(new_array)
print(output_array)

[ True  True  True  True  True False  True  True False]
[12 46 52 78 62 32 52]


In [34]:
# Write a Program to return only largest value than 52

In [41]:
my_array = np.array([12,46,96,78,62,75,32,52,17])

sorted_array = np.sort(my_array)
print(sorted_array)

new_array = sorted_array > 52
output_array = sorted_array[new_array]

print(new_array)
print(output_array)

[12 17 32 46 52 62 75 78 96]
[False False False False False  True  True  True  True]
[62 75 78 96]


In [42]:
import random

In [44]:
# help(random)

In [50]:
x = random.rand[0.31743278 0.81644155 0.64811609 0.36600979 0.2297195  0.55503524
 0.4897612  0.22505677 0.27197916 0.92378739]int(0,100)
print(x)

69


In [48]:
from numpy import random

In [53]:
x = random.rand(10)
print(x)

[0.31743278 0.81644155 0.64811609 0.36600979 0.2297195  0.55503524
 0.4897612  0.22505677 0.27197916 0.92378739]
